import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Pineapple Dashboard - Authorization",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex items-center justify-center h-screen bg-neutral-950">
      {children}
    </div>
  );
}
